# Generated by Django 4.2.6 on 2023-11-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poketmon", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="monster",
            name="ability",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="monster",
            name="height",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="monster",
            name="weight",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=10, null=True
            ),
        ),
    ]
