# Generated by Django 4.2.6 on 2023-11-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poketmon", "0002_monster_ability_monster_height_monster_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monster",
            name="height",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="monster",
            name="weight",
            field=models.FloatField(default=None, null=True),
        ),
    ]
